#!/usr/bin/env python3
"""Verify that the W114 level-57 standard relation word is generated by
Otsubo-Yamazaki motivic reflection and n=3 multiplication relations.

This does not trace an explicit Chow cycle. It verifies the exact combinatorial
hypotheses needed to lift each standard relation generator to the motivic
relation families of Otsubo-Yamazaki.
"""
from __future__ import annotations
import json

M = 57
GAMMA_A = (4, 11, 16, 17)
REFLECTION_A = (22, 25, 28)

def mod(a): return a % M

def reflection_relation(a):
    a=mod(a)
    if a==0:
        raise ValueError("reflection requires nonzero residue")
    return (a, mod(-a))

def multiplication_relation_n3(a):
    a=mod(a)
    if a==0:
        raise ValueError("multiplication relation requires nonzero a")
    # theta(3a)=theta(a)+theta(a+19)+theta(a+38);
    # after reflection theta(-3a)=-theta(3a):
    # theta(a)+theta(a+19)+theta(a+38)+theta(-3a)=0.
    return (a, mod(a+19), mod(a+38), mod(-3*a))

def theorem_1_1_ii_hypothesis(a):
    # For alpha = chi_57^a and n=3, alpha^3 != 1 iff 19 does not divide a.
    return mod(a) != 0 and mod(a) % 19 != 0

def run():
    reflections=[]
    for a in REFLECTION_A:
        reflections.append({
            "a":a,
            "relation":list(reflection_relation(a)),
            "motivic_lift":"reflection relation / Proposition 4.11(4.8)",
            "hypothesis":"PASS",
        })

    multiplications=[]
    for a in GAMMA_A:
        rel=multiplication_relation_n3(a)
        if not theorem_1_1_ii_hypothesis(a):
            raise AssertionError(f"Theorem 1.1(ii) n=3 hypothesis fails for a={a}")
        if rel != (a, mod(a+19), mod(a+38), mod(-3*a)):
            raise AssertionError("gamma relation mismatch")
        multiplications.append({
            "a":a,
            "relation":list(rel),
            "alpha_cubed_nontrivial":"PASS",
            "motivic_lift":"Theorem 1.1(ii), n=3, d=57 + reflection normalization",
        })

    expected = {
        4:[4,23,42,45],
        11:[11,30,49,24],
        16:[16,35,54,9],
        17:[17,36,55,6],
    }
    for item in multiplications:
        if item["relation"] != expected[item["a"]]:
            raise AssertionError(f"unexpected gamma_3 relation for a={item['a']}")

    return {
        "schema":"conscience64/w114-motivic-standard-word/v1",
        "degree":57,
        "reflection_generators":reflections,
        "multiplication_generators":multiplications,
        "exact_relation_word":(
            "alpha_S-alpha_Aoki = R(22)-R(25)-R(28)"
            "-gamma_3,4-gamma_3,11-gamma_3,16-gamma_3,17"
        ),
        "consequence":(
            "Every generator in the committed exact W114 standard-normalization "
            "relation word belongs to a relation family lifted to Chow motives by "
            "Otsubo-Yamazaki. This supplies a motive-level route for the standard "
            "part, but not yet an explicit composed Chow correspondence."
        ),
        "claim_ceiling":[
            "RELATION_FAMILY_HAS_MOTIVIC_LIFT != EXPLICIT_COMPOSED_CYCLE",
            "STANDARD_RELATION_WORD_MOTIVIC_ROUTE != MOT_1_CLOSED",
            "ARTIN_SIGN_A(3*(7-zeta_3))_REMAINS_SEPARATE_LOAD_BEARING_FACTOR",
            "REALIZATION_MATCH != CHOW_CORRESPONDENCE",
        ],
    }

if __name__=="__main__":
    print(json.dumps(run(),indent=2,sort_keys=True))
